# Generated by Django 2.1.4 on 2019-05-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motobike',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                (
                    'category',
                    models.ForeignKey(
                        db_column='category',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bikes_site.Category',
                        to_field='name',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        db_column='company',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bikes_site.Company',
                        to_field='name',
                    ),
                ),
            ],
        ),
    ]
