# Generated by Django 2.1.4 on 2019-05-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('bikes_site', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='category', name='name', field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name='company', name='name', field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name='motobike',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bikes_site.Category'
            ),
        ),
        migrations.AlterField(
            model_name='motobike',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='bikes_site.Company'
            ),
        ),
    ]
