# Generated by Django 2.1.4 on 2019-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bikes_site', '0002_auto_20190502_1312')]

    operations = [
        migrations.AddField(
            model_name='motobike',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        )
    ]
